[tools]
testez = { source = "Roblox/testez", version = "0.2.0" }
rojo = { source = "rojo-rbx/rojo", version = "7.0.0-alpha.4" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }